# Generated by Django 4.1.4 on 2022-12-09 11:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(db_index=True, default=None, help_text='4 цифры, например: 0001', max_length=4, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.MaxLengthValidator(4)], verbose_name='Серия карты')),
                ('number', models.CharField(db_index=True, default=None, help_text='12 цифр,  например: 0001000000000001', max_length=12, validators=[django.core.validators.MinLengthValidator(12), django.core.validators.MaxLengthValidator(12)], verbose_name='Номер карты')),
                ('full_number', models.CharField(default=1, max_length=12, unique=True, validators=[django.core.validators.MinLengthValidator(16), django.core.validators.MaxLengthValidator(16)])),
                ('start_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата выдачи карты')),
                ('end_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата окончания карты')),
                ('status', models.CharField(choices=[('A', 'Активна'), ('I', 'Не активна'), ('E', 'Просрочена')], default='I', max_length=1, verbose_name='Статус карты')),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата создания записи')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата ред-ия записи')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Карта',
                'verbose_name_plural': 'Карты',
                'ordering': ['end_date'],
            },
        ),
    ]
