# Generated by Django 4.1.4 on 2022-12-09 11:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='full_number',
            field=models.CharField(max_length=12, unique=True, validators=[django.core.validators.MinLengthValidator(16), django.core.validators.MaxLengthValidator(16)], verbose_name='Полный номер'),
        ),
    ]
