# Generated by Django 4.1.4 on 2022-12-12 10:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_alter_card_number_alter_card_series'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='number',
            field=models.CharField(db_index=True, default=None, help_text='12 цифр,  например: 0001000000000001', max_length=12, validators=[django.core.validators.MinLengthValidator(12), django.core.validators.MaxLengthValidator(12)], verbose_name='Номер карты'),
        ),
        migrations.AlterField(
            model_name='card',
            name='series',
            field=models.CharField(db_index=True, default=None, help_text='4 цифры, например: 0001', max_length=4, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.MaxLengthValidator(4)], verbose_name='Серия карты'),
        ),
    ]
